### Variables
@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@post_id = 698e668864d28fd219b22b54
@delete_id = 698e27cc1cbbdb505d5618b7
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwiaXNzIjoiYmxvZy1hcGkiLCJzdWIiOiI2OThiNTE4YjQyNTkwNjQzMTFjMGNlOWEiLCJleHAiOjE3NzA5NDE3MTAsImlhdCI6MTc3MDkzOTkxMH0.TdrKBjvmn18E-1dHe1SIo9ClKO65H7vk1vDw3j5LeAA


@user_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsImVtYWlsIjoidXN1YXJpb0Bjb3JyZW8uY29tIiwiaXNzIjoiYmxvZy1hcGkiLCJzdWIiOiI2OThiNTE4NjQyNTkwNjQzMTFjMGNlOTkiLCJleHAiOjE3NzA5NDUwODEsImlhdCI6MTc3MDk0MzI4MX0.NnCbIHV235RSOa0ZqJaFnO8eQrkWTfudvSHayqwSpSk


### Crear un nuevo post
POST http://{{host}}/api/v1/posts
Content-Type: application/json
Authorization: {{user_token}}

{
    "title": "Mi primer post en Go",
    "content": "Este es el contenido del blog usando MongoDB v2",
    "author": "Tu Nombre"
}

### Obtener todos los posts
GET http://{{host}}/api/v1/posts
Accept: application/json

### Obtener un post por ID
GET http://{{host}}/api/v1/posts/{{post_id}}
Accept: application/json

###Obetener posts con nombre
GET http://{{host}}/api/v1/posts/search?title=Mi%20primer%20post%20en%20Go
Accept: application/json

###Obtener posts con author
GET http://{{host}}/api/v1/posts/search?author=698b51864259064311c0ce99
Accept: application/json

### Eliminar todos los posts
DELETE http://{{host}}/api/v1/admin/posts
Accept: application/json
Authorization: {{admin_token}}

### Eliminar un post por ID
DELETE http://{{host}}/api/v1/admin/posts/{{delete_id}}
Accept: application/json
Authorization: {{admin_token}}

### Nuevo Usuario
POST http://{{host}}/api/v1/regiser
Content-Type: application/json

{
    "email":    "usuario@correo.com",
    "password": "tu_contraseña"
}

### Obtener Credenciales de Usuarios
GET http://{{host}}/api/v1/admin/users
Content-Type: application/json
Authorization: {{admin_token}}

### Login Admin
POST http://{{host}}/api/v1/login
Content-Type: application/json
Authorization: {{admin_token}}

{
    "email":    "admin@example.com",
    "password": "admin"
}

### Login Usuario
POST http://{{host}}/api/v1/login
Content-Type: application/json

{
    "email":    "usuario@correo.com",
    "password": "tu_contraseña"
}